### ISSUE TITLE
[Bug]: Trader Weapon ammunition font is wrong.....

### ISSUE THREAD

**Issue by rhtodtjs** [InsultingPros/KF2HUD#5]
### Contact Details

rhtodtjs@naver.com

### What happened?

A bug happened!

![image](https://user-images.githubusercontent.com/30650462/215508870-fce740fe-3bb4-44db-86fd-1616ba75c30b.png)

i am using scrn total pack and using steam client (not korean patched)

So small font is hard to read.... Would you help me please?...

**Comment by dkanus** [comment]
These labels don't get their font set up properly and just use whatever random garbage was left in `Canvas`. I've tried adding font cleanup where it was missing in KF2HUD, but it didn't fix this issue - seems like it works better with scrn's standard HUD because it shits the bed just right to leave proper font in `Canvas`.

The bottom line is - this is scrn issue with scrn menus.
